expr_name: 'mgpu4-batch128-width1.0-large'
headless: False

dataloader:
  basepath: "/dataset/imagenet"
  batch_size: 512
  num_workers: 16
  use_dali: False

model:
  type: small
  args:
    width_mult: 1.0
  num_classes: 1000
  pretrained:
    enabled: False
    path: '/workspace/mobilenetv3/pretrained_model.pth'


train:
  base_dir: '/workspace/mobilenetv3/outputs'
  precision: 16
  strategy: False
  gpus: 1
  epochs: 20
  ema:
    enabled: False
    decay: 0.9999
  optim:
    lr: 0.008
    weight_decay: 1e-5
    momentum: 0.1
  limit_train_batches: 1.0
  limit_val_batches: 1.0

wandb:
  enabled: True
  project: 'mobilenetv3'
  login_key: ''